# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\InstrumentLibrary-yolo\InstsAndQt\TKOscope\TK.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Oscilloscope(object):
    def setupUi(self, Oscilloscope):
        Oscilloscope.setObjectName(_fromUtf8("Oscilloscope"))
        Oscilloscope.resize(741, 543)
        self.verticalLayout = QtGui.QVBoxLayout(Oscilloscope)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Oscilloscope)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gOsc = PlotWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gOsc.sizePolicy().hasHeightForWidth())
        self.gOsc.setSizePolicy(sizePolicy)
        self.gOsc.setObjectName(_fromUtf8("gOsc"))
        self.verticalLayout_2.addWidget(self.gOsc)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gbAveraging = QtGui.QGroupBox(self.tab_5)
        self.gbAveraging.setFlat(True)
        self.gbAveraging.setCheckable(True)
        self.gbAveraging.setObjectName(_fromUtf8("gbAveraging"))
        self.horizontalLayout_53 = QtGui.QHBoxLayout(self.gbAveraging)
        self.horizontalLayout_53.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.cbAveMode = QtGui.QComboBox(self.gbAveraging)
        self.cbAveMode.setObjectName(_fromUtf8("cbAveMode"))
        self.cbAveMode.addItem(_fromUtf8(""))
        self.cbAveMode.addItem(_fromUtf8(""))
        self.horizontalLayout_53.addWidget(self.cbAveMode)
        self.sbAveNum = QtGui.QSpinBox(self.gbAveraging)
        self.sbAveNum.setProperty("value", 4)
        self.sbAveNum.setObjectName(_fromUtf8("sbAveNum"))
        self.horizontalLayout_53.addWidget(self.sbAveNum)
        self.cbRolling = QtGui.QCheckBox(self.gbAveraging)
        self.cbRolling.setObjectName(_fromUtf8("cbRolling"))
        self.horizontalLayout_53.addWidget(self.cbRolling)
        self.gridLayout_2.addWidget(self.gbAveraging, 0, 1, 1, 1)
        self.groupBox_39 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_39.setFlat(True)
        self.groupBox_39.setCheckable(False)
        self.groupBox_39.setObjectName(_fromUtf8("groupBox_39"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_39)
        self.gridLayout_9.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tFELFreq = QFNumberEdit(self.groupBox_39)
        self.tFELFreq.setObjectName(_fromUtf8("tFELFreq"))
        self.gridLayout_9.addWidget(self.tFELFreq, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_39, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.groupBox_40 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_40.setFlat(True)
        self.groupBox_40.setCheckable(False)
        self.groupBox_40.setObjectName(_fromUtf8("groupBox_40"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_40)
        self.gridLayout_10.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tRatio = QFNumberEdit(self.groupBox_40)
        self.tRatio.setObjectName(_fromUtf8("tRatio"))
        self.gridLayout_10.addWidget(self.tRatio, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_40, 0, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout_2.setColumnStretch(2, 3)
        self.gridLayout_2.setColumnStretch(3, 8)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.oscControlsWidget = QtGui.QWidget(Oscilloscope)
        self.oscControlsWidget.setObjectName(_fromUtf8("oscControlsWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.oscControlsWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.bOPause = QtGui.QPushButton(self.oscControlsWidget)
        self.bOPause.setCheckable(True)
        self.bOPause.setChecked(True)
        self.bOPause.setObjectName(_fromUtf8("bOPause"))
        self.horizontalLayout.addWidget(self.bOPause)
        self.groupBox_31 = QtGui.QGroupBox(self.oscControlsWidget)
        self.groupBox_31.setFlat(True)
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.groupBox_31)
        self.horizontalLayout_29.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.cOGPIB = QtGui.QComboBox(self.groupBox_31)
        self.cOGPIB.setObjectName(_fromUtf8("cOGPIB"))
        self.horizontalLayout_29.addWidget(self.cOGPIB)
        self.horizontalLayout.addWidget(self.groupBox_31)
        self.groupBox_32 = QtGui.QGroupBox(self.oscControlsWidget)
        self.groupBox_32.setFlat(True)
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_32)
        self.horizontalLayout_30.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.cOChannel = QtGui.QComboBox(self.groupBox_32)
        self.cOChannel.setObjectName(_fromUtf8("cOChannel"))
        self.cOChannel.addItem(_fromUtf8(""))
        self.cOChannel.addItem(_fromUtf8(""))
        self.cOChannel.addItem(_fromUtf8(""))
        self.cOChannel.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.cOChannel)
        self.horizontalLayout.addWidget(self.groupBox_32)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.oscControlsWidget)

        self.retranslateUi(Oscilloscope)
        self.tabWidget.setCurrentIndex(0)
        self.cOChannel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Oscilloscope)
        Oscilloscope.setTabOrder(self.tFELFreq, self.bOPause)
        Oscilloscope.setTabOrder(self.bOPause, self.cOGPIB)
        Oscilloscope.setTabOrder(self.cOGPIB, self.cOChannel)
        Oscilloscope.setTabOrder(self.cOChannel, self.gOsc)
        Oscilloscope.setTabOrder(self.gOsc, self.tabWidget)

    def retranslateUi(self, Oscilloscope):
        Oscilloscope.setWindowTitle(_translate("Oscilloscope", "Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Oscilloscope", "Waveform", None))
        self.gbAveraging.setTitle(_translate("Oscilloscope", "Averaging", None))
        self.cbAveMode.setItemText(0, _translate("Oscilloscope", "Waveform", None))
        self.cbAveMode.setItemText(1, _translate("Oscilloscope", "Peaks", None))
        self.cbRolling.setText(_translate("Oscilloscope", "Rolling", None))
        self.groupBox_39.setTitle(_translate("Oscilloscope", "FEL Freq (cm-1)", None))
        self.tFELFreq.setText(_translate("Oscilloscope", "0", None))
        self.groupBox_40.setTitle(_translate("Oscilloscope", "Ratio (%)", None))
        self.tRatio.setText(_translate("Oscilloscope", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Oscilloscope", "Misc Settings", None))
        self.bOPause.setText(_translate("Oscilloscope", "Pause", None))
        self.groupBox_31.setTitle(_translate("Oscilloscope", "GPIB", None))
        self.cOGPIB.setToolTip(_translate("Oscilloscope", "GPIB0::5::INSTR", None))
        self.groupBox_32.setTitle(_translate("Oscilloscope", "Channel", None))
        self.cOChannel.setItemText(0, _translate("Oscilloscope", "1", None))
        self.cOChannel.setItemText(1, _translate("Oscilloscope", "2", None))
        self.cOChannel.setItemText(2, _translate("Oscilloscope", "3", None))
        self.cOChannel.setItemText(3, _translate("Oscilloscope", "4", None))

from InstsAndQt.customQt import QFNumberEdit
from pyqtgraph import PlotWidget
