# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\InstrumentLibrary-yolo\InstsAndQt\DelayGenerator\delayGenerator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(248, 362)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dATime = DelayTimeEditor(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dATime.sizePolicy().hasHeightForWidth())
        self.dATime.setSizePolicy(sizePolicy)
        self.dATime.setMinimumSize(QtCore.QSize(130, 53))
        self.dATime.setMaximumSize(QtCore.QSize(130, 53))
        self.dATime.setObjectName(_fromUtf8("dATime"))
        self.gridLayout.addWidget(self.dATime, 0, 4, 1, 1)
        self.cbDRef = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDRef.sizePolicy().hasHeightForWidth())
        self.cbDRef.setSizePolicy(sizePolicy)
        self.cbDRef.setObjectName(_fromUtf8("cbDRef"))
        self.cbDRef.addItem(_fromUtf8(""))
        self.cbDRef.addItem(_fromUtf8(""))
        self.cbDRef.addItem(_fromUtf8(""))
        self.cbDRef.addItem(_fromUtf8(""))
        self.cbDRef.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbDRef, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.cbCRef = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCRef.sizePolicy().hasHeightForWidth())
        self.cbCRef.setSizePolicy(sizePolicy)
        self.cbCRef.setObjectName(_fromUtf8("cbCRef"))
        self.cbCRef.addItem(_fromUtf8(""))
        self.cbCRef.addItem(_fromUtf8(""))
        self.cbCRef.addItem(_fromUtf8(""))
        self.cbCRef.addItem(_fromUtf8(""))
        self.cbCRef.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbCRef, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.cbBRef = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbBRef.sizePolicy().hasHeightForWidth())
        self.cbBRef.setSizePolicy(sizePolicy)
        self.cbBRef.setObjectName(_fromUtf8("cbBRef"))
        self.cbBRef.addItem(_fromUtf8(""))
        self.cbBRef.addItem(_fromUtf8(""))
        self.cbBRef.addItem(_fromUtf8(""))
        self.cbBRef.addItem(_fromUtf8(""))
        self.cbBRef.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbBRef, 1, 2, 1, 1)
        self.cbARef = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbARef.sizePolicy().hasHeightForWidth())
        self.cbARef.setSizePolicy(sizePolicy)
        self.cbARef.setObjectName(_fromUtf8("cbARef"))
        self.cbARef.addItem(_fromUtf8(""))
        self.cbARef.addItem(_fromUtf8(""))
        self.cbARef.addItem(_fromUtf8(""))
        self.cbARef.addItem(_fromUtf8(""))
        self.cbARef.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbARef, 0, 2, 1, 1)
        self.dBTime = DelayTimeEditor(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dBTime.sizePolicy().hasHeightForWidth())
        self.dBTime.setSizePolicy(sizePolicy)
        self.dBTime.setMinimumSize(QtCore.QSize(130, 53))
        self.dBTime.setMaximumSize(QtCore.QSize(130, 53))
        self.dBTime.setObjectName(_fromUtf8("dBTime"))
        self.gridLayout.addWidget(self.dBTime, 1, 4, 1, 1)
        self.dDTime = DelayTimeEditor(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dDTime.sizePolicy().hasHeightForWidth())
        self.dDTime.setSizePolicy(sizePolicy)
        self.dDTime.setMinimumSize(QtCore.QSize(130, 53))
        self.dDTime.setMaximumSize(QtCore.QSize(130, 53))
        self.dDTime.setObjectName(_fromUtf8("dDTime"))
        self.gridLayout.addWidget(self.dDTime, 3, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.cbGPIB = InstrumentGPIB(self.tab)
        self.cbGPIB.setObjectName(_fromUtf8("cbGPIB"))
        self.gridLayout.addWidget(self.cbGPIB, 4, 4, 1, 1)
        self.dCTime = DelayTimeEditor(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dCTime.sizePolicy().hasHeightForWidth())
        self.dCTime.setSizePolicy(sizePolicy)
        self.dCTime.setMinimumSize(QtCore.QSize(130, 53))
        self.dCTime.setMaximumSize(QtCore.QSize(130, 53))
        self.dCTime.setObjectName(_fromUtf8("dCTime"))
        self.gridLayout.addWidget(self.dCTime, 2, 4, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.modeLabel = QtGui.QLabel(self.tab_2)
        self.modeLabel.setObjectName(_fromUtf8("modeLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.modeLabel)
        self.cbTriggerMode = QtGui.QComboBox(self.tab_2)
        self.cbTriggerMode.setObjectName(_fromUtf8("cbTriggerMode"))
        self.cbTriggerMode.addItem(_fromUtf8(""))
        self.cbTriggerMode.addItem(_fromUtf8(""))
        self.cbTriggerMode.addItem(_fromUtf8(""))
        self.cbTriggerMode.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbTriggerMode)
        self.rateLabel = QtGui.QLabel(self.tab_2)
        self.rateLabel.setObjectName(_fromUtf8("rateLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.rateLabel)
        self.tTriggerRate = QtGui.QLineEdit(self.tab_2)
        self.tTriggerRate.setObjectName(_fromUtf8("tTriggerRate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tTriggerRate)
        self.levelVLabel = QtGui.QLabel(self.tab_2)
        self.levelVLabel.setObjectName(_fromUtf8("levelVLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.levelVLabel)
        self.tTriggerLevel = QtGui.QLineEdit(self.tab_2)
        self.tTriggerLevel.setObjectName(_fromUtf8("tTriggerLevel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.tTriggerLevel)
        self.slopeLabel = QtGui.QLabel(self.tab_2)
        self.slopeLabel.setObjectName(_fromUtf8("slopeLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.slopeLabel)
        self.cbTriggerSlope = QtGui.QComboBox(self.tab_2)
        self.cbTriggerSlope.setObjectName(_fromUtf8("cbTriggerSlope"))
        self.cbTriggerSlope.addItem(_fromUtf8(""))
        self.cbTriggerSlope.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbTriggerSlope)
        self.inputLoadLabel = QtGui.QLabel(self.tab_2)
        self.inputLoadLabel.setObjectName(_fromUtf8("inputLoadLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.inputLoadLabel)
        self.cbTriggerLoad = QtGui.QComboBox(self.tab_2)
        self.cbTriggerLoad.setObjectName(_fromUtf8("cbTriggerLoad"))
        self.cbTriggerLoad.addItem(_fromUtf8(""))
        self.cbTriggerLoad.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbTriggerLoad)
        self.burstCountLabel = QtGui.QLabel(self.tab_2)
        self.burstCountLabel.setObjectName(_fromUtf8("burstCountLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.burstCountLabel)
        self.tTriggerBCount = QtGui.QLineEdit(self.tab_2)
        self.tTriggerBCount.setObjectName(_fromUtf8("tTriggerBCount"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.tTriggerBCount)
        self.burstPeriodLabel = QtGui.QLabel(self.tab_2)
        self.burstPeriodLabel.setObjectName(_fromUtf8("burstPeriodLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.burstPeriodLabel)
        self.tTriggerBPeriod = QtGui.QLineEdit(self.tab_2)
        self.tTriggerBPeriod.setObjectName(_fromUtf8("tTriggerBPeriod"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.tTriggerBPeriod)
        self.verticalLayout.addLayout(self.formLayout)
        self.bTriggerSingleShot = QtGui.QPushButton(self.tab_2)
        self.bTriggerSingleShot.setObjectName(_fromUtf8("bTriggerSingleShot"))
        self.verticalLayout.addWidget(self.bTriggerSingleShot)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 248, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DG535", None))
        self.cbDRef.setItemText(0, _translate("MainWindow", "T", None))
        self.cbDRef.setItemText(1, _translate("MainWindow", "A", None))
        self.cbDRef.setItemText(2, _translate("MainWindow", "B", None))
        self.cbDRef.setItemText(3, _translate("MainWindow", "C", None))
        self.cbDRef.setItemText(4, _translate("MainWindow", "D", None))
        self.label_2.setText(_translate("MainWindow", "+", None))
        self.label_5.setText(_translate("MainWindow", "C=", None))
        self.label_8.setText(_translate("MainWindow", "+", None))
        self.cbCRef.setItemText(0, _translate("MainWindow", "T", None))
        self.cbCRef.setItemText(1, _translate("MainWindow", "A", None))
        self.cbCRef.setItemText(2, _translate("MainWindow", "B", None))
        self.cbCRef.setItemText(3, _translate("MainWindow", "C", None))
        self.cbCRef.setItemText(4, _translate("MainWindow", "D", None))
        self.label.setText(_translate("MainWindow", "A=", None))
        self.label_7.setText(_translate("MainWindow", "+", None))
        self.label_4.setText(_translate("MainWindow", "+", None))
        self.label_6.setText(_translate("MainWindow", "D=", None))
        self.cbBRef.setItemText(0, _translate("MainWindow", "T", None))
        self.cbBRef.setItemText(1, _translate("MainWindow", "A", None))
        self.cbBRef.setItemText(2, _translate("MainWindow", "B", None))
        self.cbBRef.setItemText(3, _translate("MainWindow", "C", None))
        self.cbBRef.setItemText(4, _translate("MainWindow", "D", None))
        self.cbARef.setItemText(0, _translate("MainWindow", "T", None))
        self.cbARef.setItemText(1, _translate("MainWindow", "A", None))
        self.cbARef.setItemText(2, _translate("MainWindow", "B", None))
        self.cbARef.setItemText(3, _translate("MainWindow", "C", None))
        self.cbARef.setItemText(4, _translate("MainWindow", "D", None))
        self.label_3.setText(_translate("MainWindow", "B=", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Timings", None))
        self.modeLabel.setText(_translate("MainWindow", "Mode", None))
        self.cbTriggerMode.setItemText(0, _translate("MainWindow", "Int", None))
        self.cbTriggerMode.setItemText(1, _translate("MainWindow", "Ext", None))
        self.cbTriggerMode.setItemText(2, _translate("MainWindow", "SS", None))
        self.cbTriggerMode.setItemText(3, _translate("MainWindow", "Burst", None))
        self.rateLabel.setText(_translate("MainWindow", "Rate (Hz)", None))
        self.tTriggerRate.setText(_translate("MainWindow", "0", None))
        self.levelVLabel.setText(_translate("MainWindow", "Level (V)", None))
        self.tTriggerLevel.setText(_translate("MainWindow", "0", None))
        self.slopeLabel.setText(_translate("MainWindow", "Slope", None))
        self.cbTriggerSlope.setItemText(0, _translate("MainWindow", "Falling", None))
        self.cbTriggerSlope.setItemText(1, _translate("MainWindow", "Rising", None))
        self.inputLoadLabel.setText(_translate("MainWindow", "Input Load", None))
        self.cbTriggerLoad.setItemText(0, _translate("MainWindow", "50 Ohm", None))
        self.cbTriggerLoad.setItemText(1, _translate("MainWindow", "High Z", None))
        self.burstCountLabel.setText(_translate("MainWindow", "Burst Count", None))
        self.tTriggerBCount.setText(_translate("MainWindow", "0", None))
        self.burstPeriodLabel.setText(_translate("MainWindow", "Burst Period", None))
        self.tTriggerBPeriod.setText(_translate("MainWindow", "0", None))
        self.bTriggerSingleShot.setText(_translate("MainWindow", "Single Shot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Triggering", None))

from InstsAndQt.cQt.delayeditor import DelayTimeEditor
from InstsAndQt.instrumentgpib import InstrumentGPIB
