# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DelayGenerator\delayGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(248, 362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dATime = DelayTimeEditor(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dATime.sizePolicy().hasHeightForWidth())
        self.dATime.setSizePolicy(sizePolicy)
        self.dATime.setMinimumSize(QtCore.QSize(130, 53))
        self.dATime.setMaximumSize(QtCore.QSize(130, 53))
        self.dATime.setObjectName("dATime")
        self.gridLayout.addWidget(self.dATime, 0, 4, 1, 1)
        self.cbDRef = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDRef.sizePolicy().hasHeightForWidth())
        self.cbDRef.setSizePolicy(sizePolicy)
        self.cbDRef.setObjectName("cbDRef")
        self.cbDRef.addItem("")
        self.cbDRef.addItem("")
        self.cbDRef.addItem("")
        self.cbDRef.addItem("")
        self.cbDRef.addItem("")
        self.gridLayout.addWidget(self.cbDRef, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.cbCRef = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCRef.sizePolicy().hasHeightForWidth())
        self.cbCRef.setSizePolicy(sizePolicy)
        self.cbCRef.setObjectName("cbCRef")
        self.cbCRef.addItem("")
        self.cbCRef.addItem("")
        self.cbCRef.addItem("")
        self.cbCRef.addItem("")
        self.cbCRef.addItem("")
        self.gridLayout.addWidget(self.cbCRef, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.cbBRef = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbBRef.sizePolicy().hasHeightForWidth())
        self.cbBRef.setSizePolicy(sizePolicy)
        self.cbBRef.setObjectName("cbBRef")
        self.cbBRef.addItem("")
        self.cbBRef.addItem("")
        self.cbBRef.addItem("")
        self.cbBRef.addItem("")
        self.cbBRef.addItem("")
        self.gridLayout.addWidget(self.cbBRef, 1, 2, 1, 1)
        self.cbARef = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbARef.sizePolicy().hasHeightForWidth())
        self.cbARef.setSizePolicy(sizePolicy)
        self.cbARef.setObjectName("cbARef")
        self.cbARef.addItem("")
        self.cbARef.addItem("")
        self.cbARef.addItem("")
        self.cbARef.addItem("")
        self.cbARef.addItem("")
        self.gridLayout.addWidget(self.cbARef, 0, 2, 1, 1)
        self.dBTime = DelayTimeEditor(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dBTime.sizePolicy().hasHeightForWidth())
        self.dBTime.setSizePolicy(sizePolicy)
        self.dBTime.setMinimumSize(QtCore.QSize(130, 53))
        self.dBTime.setMaximumSize(QtCore.QSize(130, 53))
        self.dBTime.setObjectName("dBTime")
        self.gridLayout.addWidget(self.dBTime, 1, 4, 1, 1)
        self.dDTime = DelayTimeEditor(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dDTime.sizePolicy().hasHeightForWidth())
        self.dDTime.setSizePolicy(sizePolicy)
        self.dDTime.setMinimumSize(QtCore.QSize(130, 53))
        self.dDTime.setMaximumSize(QtCore.QSize(130, 53))
        self.dDTime.setObjectName("dDTime")
        self.gridLayout.addWidget(self.dDTime, 3, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.cbGPIB = InstrumentGPIB(self.tab)
        self.cbGPIB.setObjectName("cbGPIB")
        self.gridLayout.addWidget(self.cbGPIB, 4, 4, 1, 1)
        self.dCTime = DelayTimeEditor(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dCTime.sizePolicy().hasHeightForWidth())
        self.dCTime.setSizePolicy(sizePolicy)
        self.dCTime.setMinimumSize(QtCore.QSize(130, 53))
        self.dCTime.setMaximumSize(QtCore.QSize(130, 53))
        self.dCTime.setObjectName("dCTime")
        self.gridLayout.addWidget(self.dCTime, 2, 4, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.modeLabel = QtWidgets.QLabel(self.tab_2)
        self.modeLabel.setObjectName("modeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.modeLabel)
        self.cbTriggerMode = QtWidgets.QComboBox(self.tab_2)
        self.cbTriggerMode.setObjectName("cbTriggerMode")
        self.cbTriggerMode.addItem("")
        self.cbTriggerMode.addItem("")
        self.cbTriggerMode.addItem("")
        self.cbTriggerMode.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbTriggerMode)
        self.rateLabel = QtWidgets.QLabel(self.tab_2)
        self.rateLabel.setObjectName("rateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rateLabel)
        self.tTriggerRate = QtWidgets.QLineEdit(self.tab_2)
        self.tTriggerRate.setObjectName("tTriggerRate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tTriggerRate)
        self.levelVLabel = QtWidgets.QLabel(self.tab_2)
        self.levelVLabel.setObjectName("levelVLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.levelVLabel)
        self.tTriggerLevel = QtWidgets.QLineEdit(self.tab_2)
        self.tTriggerLevel.setObjectName("tTriggerLevel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tTriggerLevel)
        self.slopeLabel = QtWidgets.QLabel(self.tab_2)
        self.slopeLabel.setObjectName("slopeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.slopeLabel)
        self.cbTriggerSlope = QtWidgets.QComboBox(self.tab_2)
        self.cbTriggerSlope.setObjectName("cbTriggerSlope")
        self.cbTriggerSlope.addItem("")
        self.cbTriggerSlope.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbTriggerSlope)
        self.inputLoadLabel = QtWidgets.QLabel(self.tab_2)
        self.inputLoadLabel.setObjectName("inputLoadLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.inputLoadLabel)
        self.cbTriggerLoad = QtWidgets.QComboBox(self.tab_2)
        self.cbTriggerLoad.setObjectName("cbTriggerLoad")
        self.cbTriggerLoad.addItem("")
        self.cbTriggerLoad.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cbTriggerLoad)
        self.burstCountLabel = QtWidgets.QLabel(self.tab_2)
        self.burstCountLabel.setObjectName("burstCountLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.burstCountLabel)
        self.tTriggerBCount = QtWidgets.QLineEdit(self.tab_2)
        self.tTriggerBCount.setObjectName("tTriggerBCount")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tTriggerBCount)
        self.burstPeriodLabel = QtWidgets.QLabel(self.tab_2)
        self.burstPeriodLabel.setObjectName("burstPeriodLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.burstPeriodLabel)
        self.tTriggerBPeriod = QtWidgets.QLineEdit(self.tab_2)
        self.tTriggerBPeriod.setObjectName("tTriggerBPeriod")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tTriggerBPeriod)
        self.verticalLayout.addLayout(self.formLayout)
        self.bTriggerSingleShot = QtWidgets.QPushButton(self.tab_2)
        self.bTriggerSingleShot.setObjectName("bTriggerSingleShot")
        self.verticalLayout.addWidget(self.bTriggerSingleShot)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 248, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DG535"))
        self.cbDRef.setItemText(0, _translate("MainWindow", "T"))
        self.cbDRef.setItemText(1, _translate("MainWindow", "A"))
        self.cbDRef.setItemText(2, _translate("MainWindow", "B"))
        self.cbDRef.setItemText(3, _translate("MainWindow", "C"))
        self.cbDRef.setItemText(4, _translate("MainWindow", "D"))
        self.label_2.setText(_translate("MainWindow", "+"))
        self.label_5.setText(_translate("MainWindow", "C="))
        self.label_8.setText(_translate("MainWindow", "+"))
        self.cbCRef.setItemText(0, _translate("MainWindow", "T"))
        self.cbCRef.setItemText(1, _translate("MainWindow", "A"))
        self.cbCRef.setItemText(2, _translate("MainWindow", "B"))
        self.cbCRef.setItemText(3, _translate("MainWindow", "C"))
        self.cbCRef.setItemText(4, _translate("MainWindow", "D"))
        self.label.setText(_translate("MainWindow", "A="))
        self.label_7.setText(_translate("MainWindow", "+"))
        self.label_4.setText(_translate("MainWindow", "+"))
        self.label_6.setText(_translate("MainWindow", "D="))
        self.cbBRef.setItemText(0, _translate("MainWindow", "T"))
        self.cbBRef.setItemText(1, _translate("MainWindow", "A"))
        self.cbBRef.setItemText(2, _translate("MainWindow", "B"))
        self.cbBRef.setItemText(3, _translate("MainWindow", "C"))
        self.cbBRef.setItemText(4, _translate("MainWindow", "D"))
        self.cbARef.setItemText(0, _translate("MainWindow", "T"))
        self.cbARef.setItemText(1, _translate("MainWindow", "A"))
        self.cbARef.setItemText(2, _translate("MainWindow", "B"))
        self.cbARef.setItemText(3, _translate("MainWindow", "C"))
        self.cbARef.setItemText(4, _translate("MainWindow", "D"))
        self.label_3.setText(_translate("MainWindow", "B="))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Timings"))
        self.modeLabel.setText(_translate("MainWindow", "Mode"))
        self.cbTriggerMode.setItemText(0, _translate("MainWindow", "Int"))
        self.cbTriggerMode.setItemText(1, _translate("MainWindow", "Ext"))
        self.cbTriggerMode.setItemText(2, _translate("MainWindow", "SS"))
        self.cbTriggerMode.setItemText(3, _translate("MainWindow", "Burst"))
        self.rateLabel.setText(_translate("MainWindow", "Rate (Hz)"))
        self.tTriggerRate.setText(_translate("MainWindow", "0"))
        self.levelVLabel.setText(_translate("MainWindow", "Level (V)"))
        self.tTriggerLevel.setText(_translate("MainWindow", "0"))
        self.slopeLabel.setText(_translate("MainWindow", "Slope"))
        self.cbTriggerSlope.setItemText(0, _translate("MainWindow", "Falling"))
        self.cbTriggerSlope.setItemText(1, _translate("MainWindow", "Rising"))
        self.inputLoadLabel.setText(_translate("MainWindow", "Input Load"))
        self.cbTriggerLoad.setItemText(0, _translate("MainWindow", "50 Ohm"))
        self.cbTriggerLoad.setItemText(1, _translate("MainWindow", "High Z"))
        self.burstCountLabel.setText(_translate("MainWindow", "Burst Count"))
        self.tTriggerBCount.setText(_translate("MainWindow", "0"))
        self.burstPeriodLabel.setText(_translate("MainWindow", "Burst Period"))
        self.tTriggerBPeriod.setText(_translate("MainWindow", "0"))
        self.bTriggerSingleShot.setText(_translate("MainWindow", "Single Shot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Triggering"))

from InstsAndQt.cQt.delayeditor import DelayTimeEditor
from InstsAndQt.instrumentgpib import InstrumentGPIB
