# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lakeshore330Panel.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 20))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1, 1))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(50, 20))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.gTemp = PlotWidget(self.splitter)
        self.gTemp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gTemp.sizePolicy().hasHeightForWidth())
        self.gTemp.setSizePolicy(sizePolicy)
        self.gTemp.setMinimumSize(QtCore.QSize(1, 1))
        self.gTemp.setSizeIncrement(QtCore.QSize(1, 1))
        self.gTemp.setObjectName("gTemp")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lSampleTemp = QtWidgets.QLabel(self.layoutWidget)
        self.lSampleTemp.setMinimumSize(QtCore.QSize(110, 20))
        self.lSampleTemp.setObjectName("lSampleTemp")
        self.horizontalLayout_4.addWidget(self.lSampleTemp)
        self.tTemp = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tTemp.sizePolicy().hasHeightForWidth())
        self.tTemp.setSizePolicy(sizePolicy)
        self.tTemp.setMinimumSize(QtCore.QSize(50, 20))
        self.tTemp.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tTemp.setReadOnly(True)
        self.tTemp.setObjectName("tTemp")
        self.horizontalLayout_4.addWidget(self.tTemp)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lSetpoint = QtWidgets.QLabel(self.layoutWidget)
        self.lSetpoint.setMinimumSize(QtCore.QSize(80, 20))
        self.lSetpoint.setObjectName("lSetpoint")
        self.horizontalLayout_4.addWidget(self.lSetpoint)
        self.sbSetpoint = SpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbSetpoint.sizePolicy().hasHeightForWidth())
        self.sbSetpoint.setSizePolicy(sizePolicy)
        self.sbSetpoint.setMinimumSize(QtCore.QSize(60, 20))
        self.sbSetpoint.setObjectName("sbSetpoint")
        self.horizontalLayout_4.addWidget(self.sbSetpoint)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pHeater = QtWidgets.QProgressBar(self.layoutWidget)
        self.pHeater.setProperty("value", 38)
        self.pHeater.setTextVisible(True)
        self.pHeater.setOrientation(QtCore.Qt.Horizontal)
        self.pHeater.setInvertedAppearance(False)
        self.pHeater.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.pHeater.setObjectName("pHeater")
        self.horizontalLayout_5.addWidget(self.pHeater)
        self.cbHeater = QtWidgets.QComboBox(self.layoutWidget)
        self.cbHeater.setObjectName("cbHeater")
        self.cbHeater.addItem("")
        self.cbHeater.addItem("")
        self.cbHeater.addItem("")
        self.cbHeater.addItem("")
        self.horizontalLayout_5.addWidget(self.cbHeater)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sample Monitor"))
        self.lSampleTemp.setText(_translate("MainWindow", "Sample Temp (K):  "))
        self.lSetpoint.setText(_translate("MainWindow", "Setpoint (K):  "))
        self.cbHeater.setItemText(0, _translate("MainWindow", "Off"))
        self.cbHeater.setItemText(1, _translate("MainWindow", "Low"))
        self.cbHeater.setItemText(2, _translate("MainWindow", "Medium"))
        self.cbHeater.setItemText(3, _translate("MainWindow", "High"))

from pyqtgraph import PlotWidget, SpinBox
