# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\MotorDriver-cloaked\ControlPanel.ui'
#
# Created: Fri Apr 17 15:03:08 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(716, 455)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slideCurrent = QtWidgets.QSlider(self.groupBox)
        self.slideCurrent.setProperty("value", 0)
        self.slideCurrent.setSliderPosition(0)
        self.slideCurrent.setTracking(True)
        self.slideCurrent.setOrientation(QtCore.Qt.Horizontal)
        self.slideCurrent.setInvertedAppearance(False)
        self.slideCurrent.setInvertedControls(False)
        self.slideCurrent.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slideCurrent.setTickInterval(5)
        self.slideCurrent.setObjectName("slideCurrent")
        self.horizontalLayout.addWidget(self.slideCurrent)
        self.sbCurrent = SpinBox(self.groupBox)
        self.sbCurrent.setMaximum(100)
        self.sbCurrent.setObjectName("sbCurrent")
        self.horizontalLayout.addWidget(self.sbCurrent)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.slideStepRate = QtWidgets.QSlider(self.groupBox_5)
        self.slideStepRate.setMaximum(700)
        self.slideStepRate.setProperty("value", 0)
        self.slideStepRate.setSliderPosition(0)
        self.slideStepRate.setTracking(True)
        self.slideStepRate.setOrientation(QtCore.Qt.Horizontal)
        self.slideStepRate.setInvertedAppearance(False)
        self.slideStepRate.setInvertedControls(False)
        self.slideStepRate.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slideStepRate.setTickInterval(25)
        self.slideStepRate.setObjectName("slideStepRate")
        self.horizontalLayout_5.addWidget(self.slideStepRate)
        self.sbStepRate = SpinBox(self.groupBox_5)
        self.sbStepRate.setMaximum(100)
        self.sbStepRate.setObjectName("sbStepRate")
        self.horizontalLayout_5.addWidget(self.sbStepRate)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tVoltage = QtWidgets.QLineEdit(self.groupBox_2)
        self.tVoltage.setObjectName("tVoltage")
        self.horizontalLayout_2.addWidget(self.tVoltage)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tWA = QtWidgets.QLineEdit(self.groupBox_3)
        self.tWA.setObjectName("tWA")
        self.horizontalLayout_3.addWidget(self.tWA)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tWB = QtWidgets.QLineEdit(self.groupBox_4)
        self.tWB.setObjectName("tWB")
        self.horizontalLayout_4.addWidget(self.tWB)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_6.setStretch(0, 10)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.bOK = QtWidgets.QPushButton(Form)
        self.bOK.setObjectName("bOK")
        self.horizontalLayout_7.addWidget(self.bOK)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.setStretch(0, 10)
        self.verticalLayout_3.setStretch(1, 100)
        self.verticalLayout_3.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Motor Control", None))
        self.groupBox.setTitle(_translate("Form", "Set Current", None))
        self.groupBox_5.setTitle(_translate("Form", "Step Rate", None))
        self.groupBox_2.setTitle(_translate("Form", "Voltage", None))
        self.groupBox_3.setTitle(_translate("Form", "Winding A (A)", None))
        self.groupBox_4.setTitle(_translate("Form", "Winding B (A)", None))
        self.bOK.setText(_translate("Form", "OK", None))

from pyqtgraph import SpinBox

