# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\OscilloscopeCollection\mainWindow.ui'
#
# Created: Wed Mar 18 17:16:52 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbSettingsCH1 = QtWidgets.QGroupBox(self.tab)
        self.cbSettingsCH1.setFlat(True)
        self.cbSettingsCH1.setCheckable(True)
        self.cbSettingsCH1.setObjectName("cbSettingsCH1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cbSettingsCH1)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tSettingsCH1 = QtWidgets.QLineEdit(self.cbSettingsCH1)
        self.tSettingsCH1.setObjectName("tSettingsCH1")
        self.horizontalLayout_3.addWidget(self.tSettingsCH1)
        self.horizontalLayout.addWidget(self.cbSettingsCH1)
        self.cbSettingsCH2 = QtWidgets.QGroupBox(self.tab)
        self.cbSettingsCH2.setFlat(True)
        self.cbSettingsCH2.setCheckable(True)
        self.cbSettingsCH2.setChecked(False)
        self.cbSettingsCH2.setObjectName("cbSettingsCH2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.cbSettingsCH2)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tSettingsCH2 = QtWidgets.QLineEdit(self.cbSettingsCH2)
        self.tSettingsCH2.setObjectName("tSettingsCH2")
        self.horizontalLayout_4.addWidget(self.tSettingsCH2)
        self.horizontalLayout.addWidget(self.cbSettingsCH2)
        self.cbSettingsCH3 = QtWidgets.QGroupBox(self.tab)
        self.cbSettingsCH3.setFlat(True)
        self.cbSettingsCH3.setCheckable(True)
        self.cbSettingsCH3.setChecked(False)
        self.cbSettingsCH3.setObjectName("cbSettingsCH3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.cbSettingsCH3)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tSettingsCH3 = QtWidgets.QLineEdit(self.cbSettingsCH3)
        self.tSettingsCH3.setObjectName("tSettingsCH3")
        self.horizontalLayout_6.addWidget(self.tSettingsCH3)
        self.horizontalLayout.addWidget(self.cbSettingsCH3)
        self.cbSettingsCH4 = QtWidgets.QGroupBox(self.tab)
        self.cbSettingsCH4.setFlat(True)
        self.cbSettingsCH4.setCheckable(True)
        self.cbSettingsCH4.setChecked(False)
        self.cbSettingsCH4.setObjectName("cbSettingsCH4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.cbSettingsCH4)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tSettingsCH4 = QtWidgets.QLineEdit(self.cbSettingsCH4)
        self.tSettingsCH4.setObjectName("tSettingsCH4")
        self.horizontalLayout_5.addWidget(self.tSettingsCH4)
        self.horizontalLayout.addWidget(self.cbSettingsCH4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tSaveComments = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.tSaveComments.setObjectName("tSaveComments")
        self.horizontalLayout_9.addWidget(self.tSaveComments)
        self.horizontalLayout_13.addWidget(self.groupBox_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cbSettingsAve = QtWidgets.QGroupBox(self.tab)
        self.cbSettingsAve.setFlat(True)
        self.cbSettingsAve.setCheckable(True)
        self.cbSettingsAve.setChecked(False)
        self.cbSettingsAve.setObjectName("cbSettingsAve")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cbSettingsAve)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tSettingsAve = QINumberEdit(self.cbSettingsAve)
        self.tSettingsAve.setObjectName("tSettingsAve")
        self.horizontalLayout_7.addWidget(self.tSettingsAve)
        self.verticalLayout_5.addWidget(self.cbSettingsAve)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tSettingsSaveName = QtWidgets.QLineEdit(self.groupBox_2)
        self.tSettingsSaveName.setObjectName("tSettingsSaveName")
        self.horizontalLayout_8.addWidget(self.tSettingsSaveName)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cSettingsGPIB = QtWidgets.QComboBox(self.groupBox)
        self.cSettingsGPIB.setObjectName("cSettingsGPIB")
        self.horizontalLayout_2.addWidget(self.cSettingsGPIB)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.horizontalLayout_13.setStretch(0, 9)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tSettingsSaveDir = QtWidgets.QLineEdit(self.groupBox_4)
        self.tSettingsSaveDir.setEnabled(False)
        self.tSettingsSaveDir.setObjectName("tSettingsSaveDir")
        self.horizontalLayout_11.addWidget(self.tSettingsSaveDir)
        self.bSettingsChooseDir = QtWidgets.QPushButton(self.groupBox_4)
        self.bSettingsChooseDir.setObjectName("bSettingsChooseDir")
        self.horizontalLayout_11.addWidget(self.bSettingsChooseDir)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.hlChannels = QtWidgets.QHBoxLayout()
        self.hlChannels.setObjectName("hlChannels")
        self.verticalLayout.addLayout(self.hlChannels)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.bCHPause = QtWidgets.QPushButton(self.tab_2)
        self.bCHPause.setCheckable(True)
        self.bCHPause.setChecked(True)
        self.bCHPause.setObjectName("bCHPause")
        self.gridLayout_2.addWidget(self.bCHPause, 2, 1, 1, 1)
        self.bCHSave = QButtonDblClick(self.tab_2)
        self.bCHSave.setCheckable(True)
        self.bCHSave.setObjectName("bCHSave")
        self.gridLayout_2.addWidget(self.bCHSave, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.setStretch(0, 1000)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gBoxcar = PlotWidget(self.tab_3)
        self.gBoxcar.setObjectName("gBoxcar")
        self.verticalLayout_3.addWidget(self.gBoxcar)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cBoxcarCHX = QtWidgets.QComboBox(self.tab_3)
        self.cBoxcarCHX.setObjectName("cBoxcarCHX")
        self.horizontalLayout_10.addWidget(self.cBoxcarCHX)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.cBoxcarCHY = QtWidgets.QComboBox(self.tab_3)
        self.cBoxcarCHY.setObjectName("cBoxcarCHY")
        self.horizontalLayout_10.addWidget(self.cBoxcarCHY)
        self.horizontalLayout_10.setStretch(0, 10)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(2, 10)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bBoxcarPopout = QtWidgets.QPushButton(self.tab_3)
        self.bBoxcarPopout.setObjectName("bBoxcarPopout")
        self.gridLayout.addWidget(self.bBoxcarPopout, 0, 0, 1, 1)
        self.bBoxcarCollect = QtWidgets.QPushButton(self.tab_3)
        self.bBoxcarCollect.setCheckable(True)
        self.bBoxcarCollect.setObjectName("bBoxcarCollect")
        self.gridLayout.addWidget(self.bBoxcarCollect, 0, 1, 1, 1)
        self.bBoxcarSave = QtWidgets.QPushButton(self.tab_3)
        self.bBoxcarSave.setObjectName("bBoxcarSave")
        self.gridLayout.addWidget(self.bBoxcarSave, 1, 0, 1, 1)
        self.bBoxcarReset = QtWidgets.QPushButton(self.tab_3)
        self.bBoxcarReset.setObjectName("bBoxcarReset")
        self.gridLayout.addWidget(self.bBoxcarReset, 1, 1, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.cbSettingsCH1.setTitle(_translate("MainWindow", "Channel 1", None))
        self.tSettingsCH1.setText(_translate("MainWindow", "CH1", None))
        self.cbSettingsCH2.setTitle(_translate("MainWindow", "Channel 2", None))
        self.tSettingsCH2.setText(_translate("MainWindow", "CH2", None))
        self.cbSettingsCH3.setTitle(_translate("MainWindow", "Channel 3", None))
        self.tSettingsCH3.setText(_translate("MainWindow", "CH3", None))
        self.cbSettingsCH4.setTitle(_translate("MainWindow", "Channel 4", None))
        self.tSettingsCH4.setText(_translate("MainWindow", "CH4", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Comments", None))
        self.cbSettingsAve.setTitle(_translate("MainWindow", "Average", None))
        self.tSettingsAve.setText(_translate("MainWindow", "1", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Base Save Name", None))
        self.groupBox.setTitle(_translate("MainWindow", "Scope GPIB", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Save Directory", None))
        self.bSettingsChooseDir.setText(_translate("MainWindow", "Choose", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings", None))
        self.bCHPause.setText(_translate("MainWindow", "Pause", None))
        self.bCHSave.setText(_translate("MainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Channels", None))
        self.label.setText(_translate("MainWindow", "vs.", None))
        self.bBoxcarPopout.setText(_translate("MainWindow", "Popout", None))
        self.bBoxcarCollect.setText(_translate("MainWindow", "Collect", None))
        self.bBoxcarSave.setText(_translate("MainWindow", "Save", None))
        self.bBoxcarReset.setText(_translate("MainWindow", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Boxcar", None))

from pyqtgraph import PlotWidget

from InstsAndQt.customQt import QButtonDblClick, QINumberEdit

